language: php

dist: trusty
sudo: false

stages:
  - Code Format and Static Analysis
  - Units
  - Test CommonMark (weak)

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAILURE

  include:
    - stage: Code Format and Static Analysis
      php: 7.4
      install: composer install --prefer-dist --no-interaction --no-progress
      script:
        - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"vendor/autoload.php\"); echo Erusev\Parsedown\Parsedown::version;")" ]'
        - composer test-static -- --shepherd
        - composer test-formatting
        - composer test-dead-code


    - &MUTATION_AND_UNIT_TEST
      stage: Units
      php: 7.1
      install:
        - composer update --prefer-dist --no-interaction --no-progress
      script:
        - composer test-units
        - vendor/bin/infection --show-mutations --threads=4 --min-msi=90 --min-covered-msi=90

    - <<: *MUTATION_AND_UNIT_TEST
      php: 7.2
    - <<: *MUTATION_AND_UNIT_TEST
      php: 7.3
    - <<: *MUTATION_AND_UNIT_TEST
      php: 7.4

    - <<: *MUTATION_AND_UNIT_TEST
      php: nightly
      env: ALLOW_FAILURE
      script: composer test-units


    - &COMMONMARK_TEST
      stage: CommonMark
      name: Weak
      php: 7.4
      env: ALLOW_FAILURE
      install: composer install --prefer-dist --no-interaction --no-progress
      script:
        - composer test-commonmark-weak

    - <<: *COMMONMARK_TEST
      name: Strict
      script:
        - composer test-commonmark
